import type { IconType } from "react-icons";
import { FaGithub, FaMasksTheater } from "react-icons/fa6";
import {
  SiAstro,
  SiAuth0,
  SiCloudinary,
  SiCss,
  SiDocker,
  SiExpress,
  SiGit,
  SiGithubactions,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiReact,
  SiRender,
  SiSupabase,
  SiTypescript,
  SiVercel,
  SiVimeo,
  SiVite,
  SiVitest,
} from "react-icons/si";

/** Shared icon-key registry: `TechSkill.icon` values resolve here. */
export const techIcons: Partial<Record<string, IconType>> = {
  react: SiReact,
  nextjs: SiNextdotjs,
  astro: SiAstro,
  typescript: SiTypescript,
  javascript: SiJavascript,
  vite: SiVite,
  html5: SiHtml5,
  css3: SiCss,
  nodejs: SiNodedotjs,
  express: SiExpress,
  mongodb: SiMongodb,
  supabase: SiSupabase,
  auth0: SiAuth0,
  cloudinary: SiCloudinary,
  vimeo: SiVimeo,
  vitest: SiVitest,
  playwright: FaMasksTheater,
  git: SiGit,
  github: FaGithub,
  githubactions: SiGithubactions,
  vercel: SiVercel,
  netlify: SiNetlify,
  render: SiRender,
  docker: SiDocker,
};
